### ISSUE TITLE
decode结构体走了message send，导致crash

### ISSUE THREAD

**Issue by RhettTamp** [Pircate/CleanJSON#16]
FATAL_SIGNAL SIGABRT fault_address:0x00000001ef024dd0
Thread 0 name: com.apple.main-thread
0libsystem_kernel.dylib
___abort_with_payload (in libsystem_kernel.dylib)
1libsystem_kernel.dylib
_abort_with_payload_wrapper_internal (in libsystem_kernel.dylib)
2libsystem_kernel.dylib
_abort_with_payload_wrapper_internal (in libsystem_kernel.dylib)
3libobjc.A.dylib
_objc_fatalv(unsigned long long, unsigned long long, char const*, char*) (in libobjc.A.dylib)
4libobjc.A.dylib
___objc_error (in libobjc.A.dylib)
5libobjc.A.dylib
_lookUpImpOrForward (in libobjc.A.dylib)
6libobjc.A.dylib
__objc_msgSend_uncached (in libobjc.A.dylib)
7libswiftCore.dylib
_swift_instantiateObjCClass (in libswiftCore.dylib)
8libswiftCore.dylib
_swift_initClassMetadataImpl(swift::TargetClassMetadata<swift::InProcess>*, swift::ClassLayoutFlags, unsigned long, swift::TypeLayout const* const*, unsigned long*, bool) (in libswiftCore.dylib)
9libswiftCore.dylib
type metadata completion function for _KeyedDecodingContainerBox (in libswiftCore.dylib)
10libswiftCore.dylib
swift::MetadataCacheEntryBase<(anonymous namespace)::GenericCacheEntry, void const*>::doInitialization(swift::ConcurrencyControl&, swift::MetadataCompletionQueueEntry*, swift::MetadataRequest) (in libswiftCore.dylib)
11libswiftCore.dylib
_swift_getGenericMetadata (in libswiftCore.dylib)
12libswiftCore.dylib
KeyedDecodingContainer.init<A>(A1) (in libswiftCore.dylib)
1 MyProj
_CleanJSONDecoder.container<A>(keyedBy: A.Type) (in MyProj) _CleanJSONDecoder.swift:75
1 MyProj
protocol witness for Decoder.container<A>(keyedBy: A1.Type) in conformance _CleanJSONDecoder (in MyProj) <compiler-generated>:0
15libswiftCore.dylib
dispatch thunk of Decoder.container<A>(keyedBy: A1.Type) (in libswiftCore.dylib)
1 MyProj
specialized GradeTab.init(from: Decoder) (in MyProj) <compiler-generated>:0
1 MyProj
protocol witness for Decodable.init(from: Decoder) in conformance GradeTab (in MyProj) <compiler-generated>:0
18libswiftCore.dylib
dispatch thunk of Decodable.init(from: Decoder) (in libswiftCore.dylib)
1 MyProj
_CleanJSONDecoder.unbox_(_: Any, as: Decodable.Type) (in MyProj) _CleanJSONDecoder+Unbox.swift:475
2 MyProj
_CleanJSONDecoder.unbox<A>(_: Any, as: A.Type) (in MyProj) _CleanJSONDecoder+Unbox.swift:454
2 MyProj
CleanJSONUnkeyedDecodingContainer.decode<A>(A.Type) (in MyProj) CleanJSONUnkeyedDecodingContainer.swift:411
2 MyProj
protocol witness for UnkeyedDecodingContainer.decode<A>(A1.Type) in conformance CleanJSONUnkeyedDecodingContainer (in MyProj) <compiler-generated>:0
23libswiftCore.dylib
Array<A>.init(from: Decoder) (in libswiftCore.dylib)
24libswiftCore.dylib
protocol witness for Decodable.init(from: Decoder) in conformance <A> [A] (in libswiftCore.dylib)
25libswiftCore.dylib
protocol witness for Decodable.init(from: Decoder) in conformance <A> [A] (in libswiftCore.dylib)
26libswiftCore.dylib
dispatch thunk of Decodable.init(from: Decoder) (in libswiftCore.dylib)
2 MyProj
_CleanJSONDecoder.unbox_(_: Any, as: Decodable.Type) (in MyProj) _CleanJSONDecoder+Unbox.swift:475
2 MyProj
_CleanJSONDecoder.unbox<A>(_: Any, as: A.Type) (in MyProj) _CleanJSONDecoder+Unbox.swift:454
2 MyProj
decodeObject #1 <A><A1>(from: _CleanJSONDecoder) in CleanJSONKeyedDecodingContainer.decodeIfPresent<A>(_: A1.Type, forKey: A) (in MyProj) CleanJSONKeyedDecodingContainer.swift:886
3 MyProj
protocol witness for KeyedDecodingContainerProtocol.decodeIfPresent<A>(_: A1.Type, forKey: A.Key) in conformance CleanJSONKeyedDecodingContainer<A> (in MyProj) <compiler-generated>:870
31libswiftCore.dylib
_KeyedDecodingContainerBox.decodeIfPresent<A>(_: A1.Type, forKey: A.Key) (in libswiftCore.dylib)
32libswiftCore.dylib
KeyedDecodingContainer.decodeIfPresent<A>(_: A1.Type, forKey: A) (in libswiftCore.dylib)
3 MyProj
specialized PARespCourseSelectTabsConfigModel.init(from: Decoder) (in MyProj) <compiler-generated>:0
3 MyProj
protocol witness for Decodable.init(from: Decoder) in conformance PARespCourseSelectTabsConfigModel (in MyProj) <compiler-generated>:0
35libswiftCore.dylib
dispatch thunk of Decodable.init(from: Decoder) (in libswiftCore.dylib)
3 MyProj
_CleanJSONDecoder.unbox_(_: Any, as: Decodable.Type) (in MyProj) _CleanJSONDecoder+Unbox.swift:475
3 MyProj
_CleanJSONDecoder.unbox<A>(_: Any, as: A.Type) (in MyProj) _CleanJSONDecoder+Unbox.swift:454
3 MyProj
CleanJSONDecoder.decode<A>(_: A.Type, from: Any) (in MyProj) CleanJSONDecoder.swift:113
3 MyProj
CleanJSONDecoder.decode<A>(_: A.Type, from: JSONContainerConvertible) (in MyProj) CleanJSONDecoder.swift:101
4 MyProj
xxxStruct.transModel<A>(_: A.Type, withKeyValues: [String : Any]) (in MyProj) xxx.swift:208

**Comment by Pircate** [comment]
可以提供一下你的结构体吗

**Comment by RhettTamp** [comment]
> 可以提供一下你的结构体吗
```

struct Model: Codable {
    let gradeTabs: [GradeTab]?
    let grades: [Grade]?
    let iosConfig: IOSConfig?

    enum CodingKeys: String, CodingKey {
        case gradeTabs = "grade_tabs"
        case grades
        case iosConfig = "ios"
    }
}
```

**Comment by Pircate** [comment]
这样看不出问题，是否可以提供一个能跑起来的Demo。
