### ISSUE TITLE
很长的数字类型转String时，是不是有点问题？

### ISSUE THREAD

**Issue by OneTaoist** [Pircate/CleanJSON#18]
本demo中，测试结果如下：

![image](https://user-images.githubusercontent.com/18243933/131313233-4ad20bec-9354-4313-8668-0423ad66d7cc.png)

![image](https://user-images.githubusercontent.com/18243933/131313308-be7d39cc-4978-4ed2-87e1-36c6c872419d.png)

看一看？

**Comment by Pircate** [comment]
感谢反馈！1.0.9 版本已修复

**Comment by OneTaoist** [comment]
> 感谢反馈！1.0.9 版本已修复

效率很高，点赞👍！这个库很不错滴，可以添加一些 项目中经常使用到的自定义adapter类的方法吗，便于我们业务上去选择使用。

**Comment by Pircate** [comment]
> > 感谢反馈！1.0.9 版本已修复
> 
> 效率很高，点赞👍！这个库很不错滴，可以添加一些 项目中经常使用到的自定义adapter类的方法吗，便于我们业务上去选择使用。

没办法考虑到所有人的需求，所以开放了接口让外部去自定义 adapter
