### ISSUE TITLE
[!] No `Podfile' found in the project directory.

### ISSUE THREAD

**Issue by banzhuan-jing** [Pircate/CleanJSON#2]
么有Podfile文件.

**Comment by Pircate** [comment]
@Adrift001  先 pod repo update 更新一下本地仓库

**Comment by banzhuan-jing** [comment]
没用.

**Comment by Pircate** [comment]
@Adrift001 你不会在我这个仓库pod install吧

**Comment by banzhuan-jing** [comment]
不然呢? 哈哈哈.没找到Example

**Comment by Pircate** [comment]
@Adrift001 都在[单元测试](https://github.com/Pircate/CleanJSON/blob/master/CleanJSONTests/CleanJSONTests.swift)里面，你点进去看看吧
