### ISSUE TITLE
标准库更新了，性能提高一倍多。

### ISSUE THREAD

**Issue by NeverAgain11** [Pircate/CleanJSON#22]
标准库 JSONDecoder 用 JSONParser 解析 json，性能提升了很多，希望有时间更新一下。

**Comment by Pircate** [comment]
收到,马上更新

**Comment by Pircate** [comment]
请问源码在什么位置, 之前的位置好像变了

**Comment by NeverAgain11** [comment]
https://github.com/apple/swift-corelibs-foundation/blob/main/Sources/Foundation/JSONDecoder.swift

**Comment by Pircate** [comment]
已适配完毕，测试几天后发布版本

**Comment by Pircate** [comment]
实践发现, 旧版本和原生的差距很小, 适配新的JSONParser性能下降很多

**Comment by NeverAgain11** [comment]
JSONParser 好像提升不高，但是新的 JSONDecoder 解析性能是强很多了。
我用 Release 模式测试过了。

**Comment by NeverAgain11** [comment]
我一开始也以为是 JSONParser 提升了很多性能，好像误导了你，抱歉

**Comment by Pircate** [comment]
JSONDecoder 的底层换成了 JSONParser 解析的

**Comment by NeverAgain11** [comment]
[JSONPerformanceIssueDemo.zip](https://github.com/Pircate/CleanJSON/files/7733352/JSONPerformanceIssueDemo.zip)

可以看看这个 demo Release 模式下的解析耗时

**Comment by Pircate** [comment]
新的 JSONDecoder 解析确实很快, 他使用 JSONParser 代替了之前的 JSONSerialization 来解析 Data, 但是在 Codable 这一层做了同样的兼容策略, 性能却比之前下降了很多.

**Comment by NeverAgain11** [comment]
猜测 JSONDecoder 本身也优化许多。
